### ISSUE TITLE
sent_exit_feedback flag not being set

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/tech-for-better-bot#32]
It looks like when the send_exit_feedback flag is being set in Airtable, sent_exit_feedback is not being  set and therefore emails are possibly not being sent.

**Comment by Oliversw** [comment]
Sorry not to see this earlier @sofer! There is also an issue with the initial notifications not being sent and I think it is due to us changing the names on Airtable. I made some changes to attempt to fix the bug on Wednesday but it obviously didn't work so I'll look into it again now.

**Comment by sofer** [comment]
Fixed by the looks of things.
