### ISSUE TITLE
Add Tech for Better Exit feedback to the workflow

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/tech-for-better-bot#9]
It would be great to include the exit feedback questionnaire as part of the process. The form and feedback are currently sitting in the "Tech for Better Exit feedback" airtable.

**Comment by charlielafosse** [comment]
Yup - similar to other parts of the app, would make sense for the form to be automatically sent out when the 'Project completed' column for that PO is ticked in the Airtable 'Applications' table?

Happy to do if that makes sense

**Comment by arrested-developer** [comment]
@charlielafosse I've got a lot of changes to merge in - didn't find enough time on my last day. Happy to go through them on Thursday - I did a lot of refactoring that should make the codebase easier to read / add to

**Comment by charlielafosse** [comment]
@arrested-developer sweet, that sounds great!

**Comment by sofer** [comment]
I have now moved the exit feedback into a new table on the Tech for Better airtable.
